apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otel-spring-boot-demo
  name: otel-spring-boot-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-spring-boot-demo
  template:
    metadata:
      labels:
        app: otel-spring-boot-demo
      annotations:
        instrumentation.opentelemetry.io/inject-java: "open-telemetry/otel-instrumentation"
    spec:
      containers:
        - image: harbor.warnerchen.com/library/otel-spring-boot-demo:v0.0.1
          imagePullPolicy: IfNotPresent
          name: otel-spring-boot-demo
          env:
          - name: JAVA_OPTS
            value: "-Xmx512m -Xms256m"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "256Mi"
