apiVersion: v1
kind: Service
metadata:
  name: otel-spring-boot-demo
  namespace: default
spec:
  ports:
    - name: port-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: otel-spring-boot-demo
  type: ClusterIP
